version: "3"

services:
  distribucio:
    image: distribucio
    ports:
      - ${APP_PORT:-8080}:8080
      - ${DEBUG_PORT:-8787}:8787
      - ${MGM_PORT:-9990}:9990
    environment:
      - JBOSS_APP_NAME=${APP_NAME:-distribucio}
      - JBOSS_DB_DRIVER=${DB_DRIVER:-oracle}
      - JBOSS_DB_URL=${DB_URL:-jdbc:oracle:thin:@10.35.3.242:1521:orcl}
      - JBOSS_DB_USERNAME=${DB_USERNAME:-distribucio}
      - JBOSS_DB_PASSWORD=${DB_PASSWORD:-distribucio}
      - JBOSS_AUTH_URL=${AUTH_URL:-https://authdev.limit.es}
      - JBOSS_AUTH_REALM=${AUTH_REALM:-GOIB}
      - JBOSS_AUTH_CLIENTID=${AUTH_CLIENTID:-goib-default}
      - JBOSS_MAIL_HOST=${MAIL_HOST:-correu.limit.es}
      - JBOSS_MAIL_PORT=${MAIL_PORT:-465}
      - JBOSS_MAIL_USERNAME=${MAIL_USERNAME:-proves_limit@limit.es}
      - JBOSS_MAIL_PASSWORD=${MAIL_PASSWORD:-R8lmu-98TRN}
      - JBOSS_MAIL_SSL=${MAIL_SSL:-true}
      - JBOSS_MAIL_TLS=${MAIL_TLS:-true}
      - JBOSS_PROXY_HOST=${PROXY_HOST:-}
      - JBOSS_PROXY_PORT=${PROXY_PORT:-}
      - spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:-org.hibernate.dialect.Oracle12cDialect}
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_URL:-https://authdev.limit.es}/realms/${AUTH_REALM:-GOIB}
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_URL:-https://authdev.limit.es}/realms/${AUTH_REALM:-GOIB}/protocol/openid-connect/certs
      - es.caib.distribucio.files.path=/home/jboss/apps/distribucio
      - DEBUG=${DEBUG:-true}
      - DEBUG_PORT=${DEBUG_HOST:-0.0.0.0:}${DEBUG_PORT:-8787}
    restart: always
