-- #141 Revisar el sistema de logs
-- Creació d'una nova taula de paràmetres dels logs i traspàs de dades cap a la nova taula.
 
CREATE TABLE DIS_CONT_LOG_PARAM
(
    ID NUMBER(19) NOT NULL,
    CONT_LOG_ID NUMBER(19) NOT NULL,
    NUMERO NUMBER(19) NOT NULL,
    VALOR VARCHAR2(256) NOT NULL,
    CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP(6)
);
ALTER TABLE DIS_CONT_LOG_PARAM ADD CONSTRAINT DIS_CONT_LOG_PARAM_PK PRIMARY KEY (ID);
ALTER TABLE DIS_CONT_LOG_PARAM ADD CONSTRAINT DIS_CONT_LOG_CONT_LOG_PARAM_FK FOREIGN KEY (CONT_LOG_ID) REFERENCES DIS_CONT_LOG(ID);
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_LOG_PARAM TO WWW_DISTRIBUCIO;


-- DIS_CONT_LOG.PARAM1
insert into DIS_CONT_LOG_PARAM (ID, CONT_LOG_ID, NUMERO, VALOR) 
(
	SELECT 
			HIBERNATE_SEQUENCE.nextval,
			l.id,
			1 AS numero,
			l.PARAM1 AS valor
	FROM DIS_CONT_LOG l
    WHERE l.PARAM1 IS NOT NULL
);

-- DIS_CONT_LOG.PARAM2
insert into DIS_CONT_LOG_PARAM (ID, CONT_LOG_ID, NUMERO, VALOR) 
(
	SELECT 
			HIBERNATE_SEQUENCE.nextval,
			l.id,
			2 AS numero,
			l.PARAM2 AS valor
	FROM DIS_CONT_LOG l
    WHERE l.PARAM2 IS NOT NULL
);
