-- Sentencia sql per crear la taula dis_procediment amb una fk a l'unitat organitzativa

-- Oracle --
CREATE TABLE DIS_PROCEDIMENT 
(
  ID						NUMBER(19)	    	NOT NULL,
  CODI          			VARCHAR2(64)		NOT NULL,
  NOM						VARCHAR2(256),
  CODISIA					VARCHAR2(64),
  ID_UNITAT_ORGANITZATIVA	NUMBER(19),
  ENTITAT					NUMBER(19),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);
ALTER TABLE DIS_PROCEDIMENT ADD (
  CONSTRAINT DIS_PROCEDIMENT_PK PRIMARY KEY (ID));

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_UNITAT_FK 
	FOREIGN KEY (ID_UNITAT_ORGANITZATIVA) REFERENCES DIS_UNITAT_ORGANITZATIVA(ID);

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_ENTITAT_FK 
	FOREIGN KEY (ENTITAT) REFERENCES DIS_ENTITAT(ID);
	
	
-- Postgres --	
CREATE TABLE DIS_PROCEDIMENT 
(
  ID						BIGSERIAL(19)	    	NOT NULL,
  CODI          			character varying(64),		NOT NULL,
  NOM						character varying(256),
  CODISIA					character varying(64),
  ID_UNITAT_ORGANITZATIVA	BIGSERIAL(19),
  ENTITAT					BIGSERIAL(19),
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);
ALTER TABLE DIS_PROCEDIMENT ADD (
  CONSTRAINT DIS_PROCEDIMENT_PK PRIMARY KEY (ID));

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_UNITAT_FK 
	FOREIGN KEY (ID_UNITAT_ORGANITZATIVA) REFERENCES DIS_UNITAT_ORGANITZATIVA(ID);

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_ENTITAT_FK 
	FOREIGN KEY (ENTITAT) REFERENCES DIS_ENTITAT(ID);

