-- La columna tipus es començará a emplear per indicar el tipus de servei

-- Oracle
ALTER TABLE DIS_BACKOFFICE ADD TIPUS VARCHAR2(32 CHAR) DEFAULT 'SOAP' NOT NULL;

-- Postgresql
ALTER TABLE DIS_BACKOFFICE ADD TIPUS CHARACTER VARYING(32) DEFAULT 'SOAP' NOT NULL;
