-- #362 Error esborrant bústia quan hi ha moviments de registres que hi fan referència
-- Elimina las FK de la taula de moviments
-- Crea els nous camps per guardar el nom de la bústia
-- Actualitza les dades existents amb el nom de la bústia


-- Oracle
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_ORIGEN_CONTMOV_FK;
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_DESTI_CONTMOV_FK;

ALTER TABLE DIS_CONT_MOV ADD ORIGEN_NOM VARCHAR2(1024 CHAR);
ALTER TABLE DIS_CONT_MOV ADD DESTI_NOM VARCHAR2(1024 CHAR);

UPDATE DIS_CONT_MOV SET ORIGEN_NOM = (SELECT c.NOM FROM DIS_CONTINGUT c WHERE c.ID = ORIGEN_ID)
WHERE ORIGEN_ID IS NOT NULL;

UPDATE DIS_CONT_MOV SET DESTI_NOM = (SELECT c.NOM FROM DIS_CONTINGUT c WHERE c.ID = DESTI_ID)
WHERE DESTI_ID IS NOT NULL;

-- Postgres
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_ORIGEN_CONTMOV_FK;
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_DESTI_CONTMOV_FK;

ALTER TABLE DIS_CONT_MOV ADD ORIGEN_NOM character varying(1024);
ALTER TABLE DIS_CONT_MOV ADD DESTI_NOM character varying(1024);

UPDATE DIS_CONT_MOV SET ORIGEN_NOM = (SELECT c.NOM FROM DIS_CONTINGUT c WHERE c.ID = ORIGEN_ID)
WHERE ORIGEN_ID IS NOT NULL;

UPDATE DIS_CONT_MOV SET DESTI_NOM = (SELECT c.NOM FROM DIS_CONTINGUT c WHERE c.ID = DESTI_ID)
WHERE DESTI_ID IS NOT NULL;