-- #362 Error esborrant bústia quan hi ha moviments de registres que hi fan referència
-- Elimina las FK de la taula de moviments

-- Oracle
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_ORIGEN_CONTMOV_FK;
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_DESTI_CONTMOV_FK;

-- Postgres
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_ORIGEN_CONTMOV_FK;
ALTER TABLE DIS_CONT_MOV DROP CONSTRAINT DIS_DESTI_CONTMOV_FK;
