ALTER TABLE DIS_REGISTRE_ANNEX
ADD (
    SIGN_DETALLS_DESCARREGAT NUMBER(1) DEFAULT 0
);

CREATE TABLE DIS_REGISTRE_FIRMA_DETALL
(
    DATA TIMESTAMP,
    RESPONSABLE_NIF VARCHAR2(30),
    RESPONSABLE_NOM VARCHAR2(256),
    EMISSOR_CERTIFICAT VARCHAR2(2000),
    FIRMA_ID NUMBER(19),
    CREATEDBY_CODI       	VARCHAR2(64),
    CREATEDDATE          	TIMESTAMP(6),
    LASTMODIFIEDBY_CODI  	VARCHAR2(64),
    LASTMODIFIEDDATE     	TIMESTAMP(6)
);
ALTER TABLE DIS_REGISTRE_FIRMA_DETALL ADD (CONSTRAINT DIS_REGISTRE_FIRMA_DETALL_PK PRIMARY KEY (ID)); 
ALTER TABLE DIS_REGISTRE_FIRMA_DETALL ADD CONSTRAINT DIS_FIRMA_REGISTRE_DETALL_FK FOREIGN KEY (FIRMA_ID) REFERENCES DIS_REGISTRE_ANNEX_FIRMA;

ALTER TABLE DIS_REGISTRE_ANNEX MODIFY FIRMA_CSV VARCHAR2(256);


