ALTER TABLE DIS_REGISTRE
ADD (
    JUSTIFICANT_DESCARREGAT NUMBER(1) DEFAULT 0
);
ALTER TABLE DIS_REGISTRE
ADD (
    JUSTIFICANT_ID NUMBER(19)
);
ALTER TABLE DIS_REGISTRE ADD CONSTRAINT DIS_JUSTIFICANT_REGISTRE_FK FOREIGN KEY (JUSTIFICANT_ID) REFERENCES DIS_REGISTRE_ANNEX;
ALTER TABLE DIS_REGISTRE_ANNEX MODIFY (SICRES_TIPUS_DOC NULL);
ALTER TABLE DIS_REGISTRE_ANNEX DROP CONSTRAINT DIS_REGANX_MULT_UK;

