
CREATE TABLE DIS_BACKOFFICE
(
    ID NUMBER(19) NOT NULL,
    TIPUS VARCHAR2(256 CHAR) NOT NULL,
    CODI VARCHAR2(20 CHAR) NOT NULL,
    NOM VARCHAR2(64 CHAR) NOT NULL,
    URL VARCHAR2(256 CHAR) NOT NULL,
    USUARI VARCHAR2(64 CHAR),
    CONTRASENYA VARCHAR2(64 CHAR),
    INTENTS NUMBER(10,0),
    TEMPS_ENTRE_INTENTS NUMBER(10,0),
    ENTITAT_ID NUMBER(19) NOT NULL,
    CREATEDBY_CODI VARCHAR2(64 CHAR),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR),
    LASTMODIFIEDDATE TIMESTAMP(6)
);

ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_BACKOFFICE_PK PRIMARY KEY (ID);

ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_ENTITAT_BACKOFFICE_FK FOREIGN KEY (ENTITAT_ID) REFERENCES DIS_ENTITAT(ID);
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BACKOFFICE TO WWW_DISTRIBUCIO;

-- 1 Afegeix els nous backoffices a la taula de backoffices
INSERT INTO DIS_BACKOFFICE
(
    ID,
    TIPUS,
    CODI,
    NOM,
    URL,
    USUARI,
    CONTRASENYA,
    INTENTS,
    TEMPS_ENTRE_INTENTS,
    ENTITAT_ID,
    CREATEDBY_CODI,
    CREATEDDATE
)
(
	SELECT
		DIS_HIBERNATE_SEQ.nextval,
	    TIPUS,
	    CODI,
	    NOM,
	    URL,
	    USUARI,
	    CONTRASENYA,
	    INTENTS,
	    TEMPS_ENTRE_INTENTS,
	    ENTITAT_ID,
	    CREATEDBY_CODI,
	    CREATEDDATE
	FROM (
		SELECT
		    NVL(r.TIPUS_BACKOFFICE, 'DISTRIBUCIO') TIPUS ,
		    NVL(r.BACKOFFICE_CODI, NOM) CODI,
		    NOM,
		    NVL(URL, 'http://camp.obligatori') URL,
		    USUARI,
		    CONTRASENYA,
		    INTENTS,
		    TEMPS_ENTRE_INTENTS,
		    ENTITAT_ID,
		    CREATEDBY_CODI,
		    CREATEDDATE
		FROM DIS_REGLA r
		WHERE r.TIPUS = 'BACKOFFICE'
	)
);

-- 2 Actualitza la referència de les regles tipus bakcoffice amb el registre que li toqui
UPDATE DIS_REGLA r SET BACKOFFICE_DESTI_ID = 
( 
	SELECT ID 
	FROM DIS_BACKOFFICE b
	WHERE ROWNUM = 1
	 	AND r.TIPUS_BACKOFFICE = b.TIPUS 
	 	AND (r.BACKOFFICE_CODI = b.CODI OR (r.BACKOFFICE_CODI IS NULL AND r.NOM = b.NOM ))
	 	AND r.NOM = b.NOM 
	 	AND r.URL = b.URL 
);
