ALTER TABLE DIS_REGLA
ADD (
    BUSTIA_FILTRE_ID NUMBER(19),
    BACKOFFICE_DESTI_ID NUMBER(19)
);

ALTER TABLE DIS_REGLA ADD CONSTRAINT DIS_BUSTIA_FILTRE_REGLA_FK FOREIGN KEY (BUSTIA_FILTRE_ID) REFERENCES DIS_BUSTIA(ID);
ALTER TABLE DIS_REGLA ADD CONSTRAINT DIS_BACKOFFICE_DESTI_REGLA_FK FOREIGN KEY (BACKOFFICE_DESTI_ID) REFERENCES DIS_BACKOFFICE(ID);
