-- #250: Ampliació de la columna DIS_REGISTRE.UNITAT_ADM_DESC per igualar-la a DIS_UNITAT_ORGANITZATIVA.DENOMINACIO

-- Oracle:

ALTER TABLE DIS_REGISTRE MODIFY UNITAT_ADM_DESC VARCHAR2(300 CHAR);


-- Postgresql:

ALTER TABLE DIS_REGISTRE ALTER COLUMN UNITAT_ADM_DESC TYPE CHARACTER VARYING(300);