<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.caib.distribucio</groupId>
		<artifactId>distribucio</artifactId>
		<version>1.1.1</version>
	</parent>
	<artifactId>distribucio-ear</artifactId>
	<packaging>ear</packaging>
	<properties>
		<docker.image.name>goib/${project.parent.artifactId}</docker.image.name>
		<docker.image.from>docker.io/goib/jboss-eap72-openshift-base:latest</docker.image.from>
		<docker.image.platform>linux/amd64</docker.image.platform>
		<docker.image.context>${project.basedir}/target/docker-ctx</docker.image.context>
		<docker.image.dockerfile>${project.basedir}/target/docker-ctx/Dockerfile.maven</docker.image.dockerfile>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-api-externa</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-api-interna</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-ws</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-back</artifactId>
			<version>${project.version}</version>
			<type>war</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-ejb</artifactId>
			<version>${project.version}</version>
			<type>ejb</type>
		</dependency>
		<!-- Dependències pels wars de tipus skinny 
		     (https://maven.apache.org/plugins/maven-war-plugin/examples/skinny-wars.html) -->
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-api-externa</artifactId>
			<version>${project.version}</version>
			<classifier>classes</classifier>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-api-interna</artifactId>
			<version>${project.version}</version>
			<classifier>classes</classifier>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-back</artifactId>
			<version>${project.version}</version>
			<classifier>classes</classifier>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-service-intf</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-backend</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>distribucio-plugin-impl</artifactId>
			<version>${project.version}</version>
		</dependency>
		<!-- Per a solucionar "NoClassDefFoundError: org/springframework/http/server/reactive/ServletServerHttpResponse$ResponseBodyProcessor" 
			(https://developer.jboss.org/thread/276373?start=15&tstart=0) -->
		<dependency>
			<groupId>org.reactivestreams</groupId>
			<artifactId>reactive-streams</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>docker-maven-plugin</artifactId>
				<version>0.45.0</version>
				<configuration>
					<verbose>true</verbose>
					<!-- Si utilitzes Podman enlloc de docker has de descomentar la següent línia-->
					<!-- <dockerHost>unix:///run/user/1000/podman/podman.sock</dockerHost> -->
					<images>
						<image>
							<name>${docker.image.name}</name>
							<alias>${docker.image.name}</alias>
							<build>
								<dockerFile>${docker.image.dockerfile}</dockerFile>
								<contextDir>${docker.image.context}</contextDir>
								<args>
									<BASE_IMAGE>${docker.image.from}</BASE_IMAGE>
									<BASE_PLATFORM>${docker.image.platform}</BASE_PLATFORM>
								</args>
								<buildOptions>
									<platform>${docker.image.platform}</platform>
								</buildOptions>
								<tags>
									<tag>latest</tag>
									<tag>${project.version}</tag>
								</tags>
							</build>
							<run>
								<ports>
									<!-- Mapeig del port de debug -->
									<port>8787:8787</port>
								</ports>
								<env>
									<!-- Defineix les JAVA_OPTS per habilitar el debug -->
									<JAVA_OPTS>-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n</JAVA_OPTS>
								</env>
							</run>
						</image>
					</images>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>prepare-docker-context</id>
						<phase>package</phase>
						<goals><goal>copy-resources</goal></goals>
						<configuration>
							<outputDirectory>${project.build.directory}/docker-ctx</outputDirectory>
							<overwrite>true</overwrite>
							<resources>
								<resource>
									<directory>${project.basedir}/src/main/docker</directory>
									<includes>
										<include>config/standalone-openshift.xml</include>
										<include>config/jboss_config.sh</include>
										<include>Dockerfile.maven</include>
									</includes>
									<filtering>false</filtering>
								</resource>
								<resource>
									<directory>${project.basedir}/docker/properties</directory>
									<targetPath>properties</targetPath>
									<filtering>false</filtering>
								</resource>
								<resource>
									<directory>${project.build.directory}</directory>
									<includes>
										<include>distribucio.ear</include>
									</includes>
									<filtering>false</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>3.2.0</version>
				<configuration>
					<generateApplicationXml>true</generateApplicationXml>
					<defaultLibBundleDir>/lib</defaultLibBundleDir>
					<includeLibInApplicationXml>false</includeLibInApplicationXml>
					<version>6</version>
					<initializeInOrder>true</initializeInOrder>
					<skinnyWars>true</skinnyWars>
					<packagingExcludes>lib/es.caib.distribucio-distribucio-api-*,lib/es.caib.distribucio-distribucio-back-*,lib/org.apache.cxf-cxf*</packagingExcludes>
					<archive>
						<manifestEntries>
							<Build-Timestamp>${maven.build.timestamp}</Build-Timestamp>
							<Implementation-Vendor>Límit Tecnologies</Implementation-Vendor>
							<Implementation-Version>${project.version}</Implementation-Version>
							<Implementation-SCM-Branch>${git.branch}</Implementation-SCM-Branch>
							<Implementation-SCM-Revision>${git.commit.id}</Implementation-SCM-Revision>
						</manifestEntries>
					</archive>
					<modules>
						<ejbModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>distribucio-ejb</artifactId>
							<bundleFileName>distribucio-ejb.jar</bundleFileName>
						</ejbModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>distribucio-api-externa</artifactId>
							<contextRoot>/distribucioapi/externa</contextRoot>
							<bundleFileName>distribucio-api-externa.war</bundleFileName>
						</webModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>distribucio-api-interna</artifactId>
							<contextRoot>/distribucioapi/interna</contextRoot>
							<bundleFileName>distribucio-api-interna.war</bundleFileName>
						</webModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>distribucio-ws</artifactId>
							<contextRoot>/distribucio/ws</contextRoot>
							<bundleFileName>distribucio-ws.war</bundleFileName>
						</webModule>
						<webModule>
							<groupId>${project.groupId}</groupId>
							<artifactId>distribucio-back</artifactId>
							<contextRoot>/distribucioback</contextRoot>
							<bundleFileName>distribucio-back.war</bundleFileName>
						</webModule>
					</modules>
				</configuration>
			</plugin>
		</plugins>
		<finalName>distribucio</finalName>
	</build>
</project>