UPDATE DIS_REGISTRE SET PROCES_ESTAT = 'BUSTIA_PROCESSADA' WHERE PROCES_ESTAT = 'DISTRIBUIT_PROCESSAT';
UPDATE DIS_REGISTRE SET PROCES_ESTAT = 'BACK_PROCESSADA' WHERE PROCES_ESTAT = 'DISTRIBUIT_BACKOFFICE';



ALTER TABLE DIS_REGISTRE
  ADD (BACK_PENDENT_DATA TIMESTAMP(6),
       BACK_REBUDA_DATA TIMESTAMP(6),
	   BACK_PROCES_REBUTJ_ERROR_DATA TIMESTAMP(6),
	   BACK_OBSERVACIONS VARCHAR2(1024),
	   BACK_RETRY_ENVIAR_DATA TIMESTAMP(6)
	   );

	   
	   