GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ALERTA TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_USUARI TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ENTITAT TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONTINGUT TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_MOV TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_MOV_EMAIL TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_LOG TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BUSTIA TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE_ANNEX TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE_ANNEX_FIRMA TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE_INTER TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGLA TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_COMMENT TO DISTRIBUCIO;

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_CLASS TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_ENTRY TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_OBJECT_IDENTITY TO DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_SID TO DISTRIBUCIO;

GRANT SELECT ON DIS_ACL_SID_SEQ TO DISTRIBUCIO;
GRANT SELECT ON DIS_ACL_CLASS_SEQ TO DISTRIBUCIO;
GRANT SELECT ON DIS_ACL_OBJECT_IDENTITY_SEQ TO DISTRIBUCIO;
GRANT SELECT ON DIS_ACL_ENTRY_SEQ TO DISTRIBUCIO;

GRANT SELECT ON HIBERNATE_SEQUENCE TO DISTRIBUCIO;
