CREATE TABLESPACE DISTRIBUCIO
 LOGGING
  DATAFILE 'DISTRIBUCIO.ORA'
SIZE 1024M REUSE  AUTOEXTEND  ON NEXT  1024K MAXSIZE  32767M
DEFAULT  STORAGE ( INITIAL 40K NEXT 40K MINEXTENTS 1 MAXEXTENTS  2147483645 PCTINCREASE 50 );

CREATE USER distribucio identified by distribucio default tablespace DISTRIBUCIO TEMPORARY TABLESPACE temp;
GRANT CONNECT, RESOURCE, CREATE PUBLIC SYNONYM, drop public synonym, UNLIMITED TABLESPACE TO DISTRIBUCIO;