GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ALERTA TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_USUARI TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ENTITAT TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONTINGUT TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_MOV TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_MOV_EMAIL TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_LOG TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_LOG_PARAM TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BUSTIA TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE_ANNEX TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE_ANNEX_FIRMA TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE_INTER TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGLA TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONT_COMMENT TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_CLASS TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_ENTRY TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_OBJECT_IDENTITY TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_ACL_SID TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_UNITAT_ORGANITZATIVA TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_UO_SINC_REL TO WWW_DISTRIBUCIO; 
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_AVIS TO WWW_DISTRIBUCIO; 
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_REGISTRE_FIRMA_DETALL TO WWW_DISTRIBUCIO; 


GRANT SELECT ON DIS_ACL_SID_SEQ TO WWW_DISTRIBUCIO;
GRANT SELECT ON DIS_ACL_CLASS_SEQ TO WWW_DISTRIBUCIO;
GRANT SELECT ON DIS_ACL_OBJECT_IDENTITY_SEQ TO WWW_DISTRIBUCIO;
GRANT SELECT ON DIS_ACL_ENTRY_SEQ TO WWW_DISTRIBUCIO;

GRANT SELECT ON DIS_HIBERNATE_SEQ TO WWW_DISTRIBUCIO;

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BACKOFFICE TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BUSTIA_FAVORIT TO WWW_DISTRIBUCIO; 

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONFIG TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONFIG_GROUP TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_CONFIG_TYPE TO WWW_DISTRIBUCIO;

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_HIS_ANOTACIO TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_HIS_ESTAT TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_HIS_BUSTIA TO WWW_DISTRIBUCIO;

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BUSTIA_DEFAULT TO WWW_DISTRIBUCIO;
