
CREATE OR REPLACE TRIGGER DIS_ACLCLA_IDGEN_TRG
BEFORE INSERT ON DIS_ACL_CLASS
FOR EACH ROW
  BEGIN
    SELECT DIS_ACL_CLASS_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;

 
CREATE OR REPLACE TRIGGER DIS_ACLENT_IDGEN_TRG
BEFORE INSERT ON DIS_ACL_ENTRY
FOR EACH ROW
  BEGIN
    SELECT DIS_ACL_ENTRY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;

 
CREATE OR REPLACE TRIGGER DIS_ACLOID_IDGEN_TRG
BEFORE INSERT ON DIS_ACL_OBJECT_IDENTITY
FOR EACH ROW
  BEGIN
    SELECT DIS_ACL_OBJECT_IDENTITY_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;

 
CREATE OR REPLACE TRIGGER DIS_ACLSID_IDGEN_TRG
BEFORE INSERT ON DIS_ACL_SID
FOR EACH ROW
  BEGIN
    SELECT DIS_ACL_SID_SEQ.NEXTVAL INTO :new.id FROM dual;
  END;
