-- #123 Eliminar obligatorietat del camp Tipo Asunto
-- Oracle
ALTER TABLE DIS_REGISTRE MODIFY (ASSUMPTE_TIPUS_CODI NULL);
-- Postgres
ALTER TABLE DIS_REGISTRE ALTER COLUMN ASSUMPTE_TIPUS_CODI DROP NOT NULL;