-- Preferencies de tema visual i estil de menu de la interficie REACT (perfil de l'usuari)
ALTER TABLE DIS_USUARI ADD TEMA_APLICACIO VARCHAR(16 CHAR);
ALTER TABLE DIS_USUARI ADD ESTIL_MENU VARCHAR(16 CHAR) DEFAULT 'TEMA' NOT NULL;

-- Camps de tema visual dark (color de fons, color de lletra i logo) per a DIS_ENTITAT
ALTER TABLE DIS_ENTITAT ADD COLOR_FONS_DARK VARCHAR(32 CHAR);
ALTER TABLE DIS_ENTITAT ADD COLOR_LLETRA_DARK VARCHAR(32 CHAR);
ALTER TABLE DIS_ENTITAT ADD LOGO_CAP_DARK BLOB;