-- Oracle:
CREATE TABLE DIS_BUSTIA_DEFAULT
(
    ID                      NUMBER(19)             NOT NULL,
    ENTITAT                 NUMBER(19)             NOT NULL,
    BUSTIA                  NUMBER(19)             NOT NULL,
    USUARI  	            VARCHAR2(64 CHAR)      NOT NULL,
    CREATEDDATE             TIMESTAMP(6),
    LASTMODIFIEDDATE        TIMESTAMP(6)
);

-- PK
ALTER TABLE DIS_BUSTIA_DEFAULT ADD (CONSTRAINT DIS_BUSTIA_DEFAULT_PK PRIMARY KEY (ID));

-- FK
ALTER TABLE DIS_BUSTIA_DEFAULT 
    ADD CONSTRAINT DIS_BUSTIA_DEF_BST_FK FOREIGN KEY (BUSTIA) REFERENCES DIS_BUSTIA(ID);
ALTER TABLE DIS_BUSTIA_DEFAULT 
    ADD CONSTRAINT DIS_BUSTIA_DEF_ENT_FK FOREIGN KEY (ENTITAT) REFERENCES DIS_ENTITAT(ID);
ALTER TABLE DIS_BUSTIA_DEFAULT 
    ADD CONSTRAINT DIS_BUSTIA_DEF_USR_FK FOREIGN KEY (USUARI) REFERENCES DIS_USUARI(CODI);
    
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BUSTIA_DEFAULT TO WWW_DISTRIBUCIO;


-- Postgresql:
CREATE TABLE DIS_BUSTIA_DEFAULT
(
    ID                      INTEGER                 NOT NULL,
    ENTITAT                 INTEGER                 NOT NULL,
    BUSTIA                  INTEGER                 NOT NULL,
    USUARI             CHARACTER VARYING(64)   NOT NULL,
    CREATEDDATE             TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDDATE        TIMESTAMP WITHOUT TIME ZONE
);

-- PK
ALTER TABLE ONLY DIS_BUSTIA_DEFAULT ADD CONSTRAINT DIS_BUSTIA_DEFAULT_PK PRIMARY KEY (ID);

-- FK
ALTER TABLE ONLY DIS_BUSTIA_DEFAULT 
    ADD CONSTRAINT DIS_BUSTIA_DEF_BST_FK FOREIGN KEY (BUSTIA) REFERENCES DIS_BUSTIA(ID);
ALTER TABLE ONLY DIS_BUSTIA_DEFAULT 
    ADD CONSTRAINT DIS_BUSTIA_DEF_ENT_FK FOREIGN KEY (ENTITAT) REFERENCES DIS_ENTITAT(ID);
ALTER TABLE ONLY DIS_BUSTIA_DEFAULT 
    ADD CONSTRAINT DIS_BUSTIA_DEF_USR_FK FOREIGN KEY (USUARI) REFERENCES DIS_USUARI(CODI);