-- Afegir una nova opció d'administrador per poder consultar l'estat de l'execució de les darreres accions massives #738

-- Oracle
CREATE TABLE DIS_EXECUCIO_MASSIVA (	
	ID 					NUMBER(19,0) NOT NULL , 
	TIPUS 				VARCHAR2(64 CHAR) NOT NULL, 
	ESTAT 				VARCHAR2(64 CHAR) NOT NULL,
	USUARI_CODI			VARCHAR2(64 CHAR) NOT NULL, 
	DATA_CREACIO		TIMESTAMP NOT NULL, 
	DATA_INICI			TIMESTAMP, 
	DATA_FINAL			TIMESTAMP, 
	ENTITAT_ID 			NUMBER(19,0) NOT NULL, 
	PARAMETRES 			VARCHAR2(2046),
	CREATEDBY_CODI 		VARCHAR2(64 CHAR), 
	CREATEDDATE 		TIMESTAMP (6), 
	LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR), 
	LASTMODIFIEDDATE 	TIMESTAMP (6)
 );

 ALTER TABLE DIS_EXECUCIO_MASSIVA ADD (
  CONSTRAINT DIS_EXECUCIO_MASSIVA_PK PRIMARY KEY (ID));
  
 -- Assigna permisos a la taula
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_EXECUCIO_MASSIVA TO WWW_DISTRIBUCIO;

-- DIS_EXECUCIO_MASSIVA foreign keys

ALTER TABLE DIS_EXECUCIO_MASSIVA ADD CONSTRAINT DIS_EXECUCIO_MASSIVA_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES DIS_ENTITAT(ID);
ALTER TABLE DIS_EXECUCIO_MASSIVA ADD CONSTRAINT DIS_EXECUCIO_MASSIVA_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES DIS_USUARI(CODI);

CREATE TABLE DIS_EXECUCIO_MASSIVA_CONT (	
	ID 					NUMBER(19,0) NOT NULL,
	EXECUCIO_MASSIVA_ID	NUMBER(19,0) NOT NULL,
	ELEMENT_ID 			NUMBER(19,0) NOT NULL,
	ELEMENT_NOM 		VARCHAR2(2046 CHAR),
	ELEMENT_TIPUS 		VARCHAR2(16 CHAR) NOT NULL
	ESTAT 				VARCHAR2(64 CHAR) NOT NULL,
	DATA_CREACIO		TIMESTAMP NOT NULL, 
	DATA_INICI			TIMESTAMP, 
	DATA_FINAL			TIMESTAMP, 
	ERROR				VARCHAR2(2046 CHAR),
	MISSATGE			VARCHAR2(2046 CHAR),
	ORDRE				NUMBER(19,0) NOT NULL,
	CREATEDBY_CODI 		VARCHAR2(64 CHAR), 
	CREATEDDATE 		TIMESTAMP (6), 
	LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR), 
	LASTMODIFIEDDATE 	TIMESTAMP (6)
 );

 ALTER TABLE DIS_EXECUCIO_MASSIVA_CONT ADD (
  CONSTRAINT DIS_EXECUCIO_MASSIVA_CONT_PK PRIMARY KEY (ID));
  
 -- Assigna permisos a la taula
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_EXECUCIO_MASSIVA_CONT TO WWW_DISTRIBUCIO;

-- DIS_EXECUCIO_MASSIVA_CONT foreign keys

ALTER TABLE DIS_EXECUCIO_MASSIVA_CONT ADD CONSTRAINT DIS_EXECUCIO_MASSIVA_CONT_MASSIVA_FK FOREIGN KEY (EXECUCIO_MASSIVA_ID) REFERENCES DIS_EXECUCIO_MASSIVA(ID);

INSERT INTO DIS_CONFIG_GROUP (CODE,PARENT_CODE,POSITION,DESCRIPTION) VALUES ('SCHEDULLED_EXECUCIONS_MASSIVES','SCHEDULLED','20','Tasca periòdica d''executar les execucions massives pendents');
INSERT INTO DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE) VALUES ('es.caib.distribucio.segonpla.interval.execucio.massiva',null,'Especificar l''expressió ''cron'' indicant l''interval de temps de les execucions de la tasca','SCHEDULLED_EXECUCIONS_MASSIVES','0','0','CRON',null,null);

-- Postgres
CREATE TABLE DIS_EXECUCIO_MASSIVA (	
	ID 					BIGSERIAL NOT NULL , 
	TIPUS 				VARCHAR(64) NOT NULL, 
	ESTAT 				VARCHAR(64) NOT NULL, 
	USUARI_CODI			VARCHAR(64) NOT NULL, 
	DATA_CREACIO		TIMESTAMP NOT NULL, 
	DATA_INICI			TIMESTAMP, 
	DATA_FINAL			TIMESTAMP, 
	ENTITAT_ID 			BIGSERIAL NOT NULL , 
	PARAMETRES 			VARCHAR(2046),
	CREATEDBY_CODI 		VARCHAR(64), 
	CREATEDDATE 		TIMESTAMP (6), 
	LASTMODIFIEDBY_CODI VARCHAR(64), 
	LASTMODIFIEDDATE 	TIMESTAMP (6)
 );
 
 ALTER TABLE DIS_EXECUCIO_MASSIVA ADD (
  CONSTRAINT DIS_EXECUCIO_MASSIVA_PK PRIMARY KEY (ID));
  
 -- Assigna permisos a la taula
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_EXECUCIO_MASSIVA TO WWW_DISTRIBUCIO;

-- DIS_EXECUCIO_MASSIVA foreign keys

ALTER TABLE DIS_EXECUCIO_MASSIVA ADD CONSTRAINT DIS_EXECUCIO_MASSIVA_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES DIS_ENTITAT(ID);
ALTER TABLE DIS_EXECUCIO_MASSIVA ADD CONSTRAINT DIS_EXECUCIO_MASSIVA_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES DIS_USUARI(CODI);

CREATE TABLE DIS_EXECUCIO_MASSIVA_CONT (	
	ID 					BIGSERIAL NOT NULL,
	EXECUCIO_MASSIVA_ID	BIGSERIAL NOT NULL,
	ELEMENT_ID 			BIGSERIAL NOT NULL UNIQUE,
	ELEMENT_NOM 		VARCHAR(2046),
	ELEMENT_TIPUS 		VARCHAR(16) NOT NULL
	ESTAT 				VARCHAR(64) NOT NULL,
	DATA_CREACIO		TIMESTAMP NOT NULL, 
	DATA_INICI			TIMESTAMP, 
	DATA_FINAL			TIMESTAMP, 
	ERROR				VARCHAR(2046),
	MISSATGE			VARCHAR(2046 CHAR),
	ORDRE				BIGSERIAL NOT NULL,
	CREATEDBY_CODI 		VARCHAR(64), 
	CREATEDDATE 		TIMESTAMP (6), 
	LASTMODIFIEDBY_CODI VARCHAR(64), 
	LASTMODIFIEDDATE 	TIMESTAMP (6)
 );

 ALTER TABLE DIS_EXECUCIO_MASSIVA_CONT ADD (
  CONSTRAINT DIS_EXECUCIO_MASSIVA_CONT_PK PRIMARY KEY (ID));
  
 -- Assigna permisos a la taula
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_EXECUCIO_MASSIVA_CONT TO WWW_DISTRIBUCIO;

-- DIS_EXECUCIO_MASSIVA_CONT foreign keys

ALTER TABLE DIS_EXECUCIO_MASSIVA_CONT ADD CONSTRAINT DIS_EXECUCIO_MASSIVA_CONT_MASSIVA_FK FOREIGN KEY (EXECUCIO_MASSIVA_ID) REFERENCES DIS_EXECUCIO_MASSIVA(ID);

INSERT INTO DIS_CONFIG_GROUP (CODE,PARENT_CODE,POSITION,DESCRIPTION) VALUES ('SCHEDULLED_EXECUCIONS_MASSIVES','SCHEDULLED','20','Tasca periòdica d''executar les execucions massives pendents');
INSERT INTO DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE) VALUES ('es.caib.distribucio.segonpla.execucio.massiva',null,'Especificar l''expressió ''cron'' indicant l''interval de temps de les execucions de la tasca','SCHEDULLED_EXECUCIONS_MASSIVES','0',false,'CRON',null,null);
