-- Millorar el rendiment del localitzador d'annotacions #740

-- Indexar les columnes d'ordre i les que s'utilitzen freqüentment per filtrar

-- Oracle
CREATE INDEX DIS_REGISTRE_NUMERO_I ON DISTRIBUCIO.DIS_REGISTRE (NUMERO);
CREATE INDEX DIS_REGISTRE_EXTRACTE_I ON DISTRIBUCIO.DIS_REGISTRE (EXTRACTE);
CREATE INDEX DIS_REGISTRE_NUM_ORIG_I ON DISTRIBUCIO.DIS_REGISTRE (NUM_ORIG);
CREATE INDEX DIS_REGISTRE_DATA_I ON DISTRIBUCIO.DIS_REGISTRE (DATA);
CREATE INDEX DIS_REGISTRE_PROCES_ESTAT_I ON DISTRIBUCIO.DIS_REGISTRE (PROCES_ESTAT);

-- Postgres
CREATE INDEX DIS_REGISTRE_NUMERO_I ON DISTRIBUCIO.DIS_REGISTRE (NUMERO);
CREATE INDEX DIS_REGISTRE_EXTRACTE_I ON DISTRIBUCIO.DIS_REGISTRE (EXTRACTE);
CREATE INDEX DIS_REGISTRE_NUM_ORIG_I ON DISTRIBUCIO.DIS_REGISTRE (NUM_ORIG);
CREATE INDEX DIS_REGISTRE_DATA_I ON DISTRIBUCIO.DIS_REGISTRE (DATA);
CREATE INDEX DIS_REGISTRE_PROCES_ESTAT_I ON DISTRIBUCIO.DIS_REGISTRE (PROCES_ESTAT);
