-- #398 Separar la secció plugins de l'aplicació de les propietats de configuració 
 
-- Oracle

DELETE FROM DIS_CONFIG_GROUP WHERE CODE LIKE 'PLUGINS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 3 WHERE CODE LIKE 'ARXIU';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 4 WHERE CODE LIKE 'UNITATS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 5 WHERE CODE LIKE 'GES_DOC';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 6 WHERE CODE LIKE 'USUARIS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 7 WHERE CODE LIKE 'DISTRIBUCIO';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 8 WHERE CODE LIKE 'PROCEDIMENTS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 9 WHERE CODE LIKE 'DADES_EXTERNES';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 10 WHERE CODE LIKE 'SIGNATURA';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 11 WHERE CODE LIKE 'VALID_SIGN';

-- PostgreSQL

DELETE FROM DIS_CONFIG_GROUP WHERE CODE LIKE 'PLUGINS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 3 WHERE CODE LIKE 'ARXIU';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 4 WHERE CODE LIKE 'UNITATS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 5 WHERE CODE LIKE 'GES_DOC';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 6 WHERE CODE LIKE 'USUARIS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 7 WHERE CODE LIKE 'DISTRIBUCIO';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 8 WHERE CODE LIKE 'PROCEDIMENTS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 9 WHERE CODE LIKE 'DADES_EXTERNES';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 10 WHERE CODE LIKE 'SIGNATURA';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 11 WHERE CODE LIKE 'VALID_SIGN';
