-- #481 Permetre cercar anotacions per procediment

CREATE TABLE DIS_PROCEDIMENT 
(
  ID						BIGSERIAL	    	NOT NULL,
  CODI          			character varying(64),		NOT NULL,
  NOM						character varying(256),
  CODISIA					character varying(64),
  ID_UNITAT_ORGANITZATIVA	BIGSERIAL,
  ENTITAT					BIGSERIAL,
  CREATEDBY_CODI       		character varying(64),
  CREATEDDATE          		timestamp without time zone,
  LASTMODIFIEDBY_CODI  		character varying(64),
  LASTMODIFIEDDATE     		timestamp without time zone
);
ALTER TABLE DIS_PROCEDIMENT ADD (
  CONSTRAINT DIS_PROCEDIMENT_PK PRIMARY KEY (ID));

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_UNITAT_FK 
	FOREIGN KEY (ID_UNITAT_ORGANITZATIVA) REFERENCES DIS_UNITAT_ORGANITZATIVA(ID);

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_ENTITAT_FK 
	FOREIGN KEY (ENTITAT) REFERENCES DIS_ENTITAT(ID);

-- #503 Implementar un nou servei REST per comunicar anotacions pendents
ALTER TABLE DIS_BACKOFFICE ADD TIPUS CHARACTER VARYING(32) DEFAULT 'SOAP' NOT NULL;


