-- #270: Color capçalera i el logo configurables


ALTER TABLE DIS_ENTITAT ADD LOGO_CAP BLOB;
ALTER TABLE ONLY DIS_ENTITAT ADD COLOR_FONS character varying(32);
ALTER TABLE ONLY DIS_ENTITAT ADD COLOR_LLETRA character varying(32);