
-- #235: Millora de regles. Manteniment de backoffices

CREATE TABLE DIS_BACKOFFICE
(
    ID BIGSERIAL NOT NULL,
    TIPUS CHARACTER VARYING(256) NOT NULL,
    CODI CHARACTER VARYING(20) NOT NULL,
    NOM CHARACTER VARYING(64) NOT NULL,
    URL CHARACTER VARYING(256) NOT NULL,
    USUARI CHARACTER VARYING(64),
    CONTRASENYA CHARACTER VARYING(64),
    INTENTS INTEGER,
    TEMPS_ENTRE_INTENTS INTEGER,
    ENTITAT_ID BIGINT NOT NULL,
    CREATEDBY_CODI CHARACTER VARYING(64 CHAR),
    CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI CHARACTER VARYING(64 CHAR),
    LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_BACKOFFICE_PK PRIMARY KEY (ID);
ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_ENTITAT_BACKOFFICE_FK FOREIGN KEY (ENTITAT_ID) REFERENCES DIS_ENTITAT(ID);



-- #237: Millora de regles. Modificar definició de la regla

ALTER TABLE DIS_REGLA
ADD (
    BUSTIA_FILTRE_ID BIGINT,
    BACKOFFICE_DESTI_ID BIGINT
);

ALTER TABLE DIS_REGLA ADD CONSTRAINT DIS_BUSTIA_FILTRE_REGLA_FK FOREIGN KEY (BUSTIA_FILTRE_ID) REFERENCES DIS_BUSTIA(ID);
ALTER TABLE DIS_REGLA ADD CONSTRAINT DIS_BACKOFFICE_DESTI_REGLA_FK FOREIGN KEY (BACKOFFICE_DESTI_ID) REFERENCES DIS_BACKOFFICE(ID);


-- #250: Ampliació de la columna DIS_REGISTRE.UNITAT_ADM_DESC per igualar-la a DIS_UNITAT_ORGANITZATIVA.DENOMINACIO

ALTER TABLE DIS_REGISTRE ALTER COLUMN UNITAT_ADM_DESC TYPE CHARACTER VARYING(300);

