--------------------- 139: Eliminar camp unitatOrganicaCodi de la bústia -------------------------------
ALTER TABLE DIS_BUSTIA
DROP (
    UNITAT_CODI
);


---------------------  141: Revisar el sistema de logs -------------------------------
CREATE TABLE DIS_CONT_LOG_PARAM
(
    ID BIGSERIAL NOT NULL,
    CONT_LOG_ID BIGINT NOT NULL,
    NUMERO BIGINT NOT NULL,
    VALOR CHARACTER VARYING(256) NOT NULL,
    CREATEDBY_CODI CHARACTER VARYING(64),
    CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI CHARACTER VARYING(64),
    LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE
);
ALTER TABLE DIS_CONT_LOG_PARAM ADD CONSTRAINT DIS_CONT_LOG_PARAM_PK PRIMARY KEY (ID);
ALTER TABLE DIS_CONT_LOG_PARAM ADD CONSTRAINT DIS_CONT_LOG_CONT_LOG_PARAM_FK FOREIGN KEY (CONT_LOG_ID) REFERENCES DIS_CONT_LOG(ID);


insert into DIS_CONT_LOG_PARAM (ID, CONT_LOG_ID, NUMERO, VALOR) 
(
	SELECT 
			nextval('HIBERNATE_SEQUENCE'),
			l.id,
			1 AS numero,
			l.PARAM1 AS valor
	FROM DIS_CONT_LOG l
    WHERE l.PARAM1 IS NOT NULL
);

insert into DIS_CONT_LOG_PARAM (ID, CONT_LOG_ID, NUMERO, VALOR) 
(
	SELECT 
			nextval('HIBERNATE_SEQUENCE'),
			l.id,
			2 AS numero,
			l.PARAM2 AS valor
	FROM DIS_CONT_LOG l
    WHERE l.PARAM2 IS NOT NULL
);