-- #295 Poder reenviar a bústies només per a coneixement

ALTER TABLE DIS_CONT_MOV ADD PER_CONEIXEMENT BOOLEAN;

-- #294 Quan es marqui un element per Coneixement/Tramitació s'afegirà text al final dels comentaris

ALTER TABLE DIS_CONT_MOV ADD COMENTARI_DESTINS character varying(256)

-- #297 Poder marcar bústies com a favorits
CREATE TABLE DIS_BUSTIA_FAVORIT
(
    ID                  BIGSERIAL        			NOT NULL, 
    BUSTIA_ID           BIGSERIAL        			NOT NULL, 
    USUARI_CODI         character varying(64)   	NOT NULL, 
	CREATEDBY_CODI      character varying(64), 
	CREATEDDATE         timestamp without time zone, 
	LASTMODIFIEDBY_CODI character varying(64), 
	LASTMODIFIEDDATE    timestamp without time zone
);

ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_BUSTIA_FAV_BUSTIA_FK FOREIGN KEY (BUSTIA_ID)
    REFERENCES DIS_BUSTIA (ID);
ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_BUSTIA_FAV_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES DIS_USUARI (CODI);
ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_USUCRE_BUSTFAV_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES DIS_USUARI (CODI);
ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_USUMOD_BUSTFAV_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES DIS_USUARI (CODI);

ALTER TABLE ONLY DIS_BUSTIA_FAVORIT 
	ADD CONSTRAINT DIS_BUSTIA_FAV_MULT_UK 
	UNIQUE (
			BUSTIA_ID, 
			USUARI_CODI);
	
CREATE INDEX DIS_BUSTIA_FAV_BUSTIA_FK_I ON DIS_BUSTIA_FAVORIT(BUSTIA_ID);
CREATE INDEX DIS_BUSTIA_FAV_USUARI_FK_I ON DIS_BUSTIA_FAVORIT(USUARI_CODI);


-- #299 Poder reservar/agafar un assentament abans de marcar-lo com a processat
ALTER TABLE DIS_REGISTRE ADD AGAFAT_PER character varying(64);

ALTER TABLE ONLY DIS_REGISTRE ADD CONSTRAINT DIS_AGAFATPER_REGISTRE_FK FOREIGN KEY (AGAFAT_PER) REFERENCES DIS_USUARI (CODI);
CREATE INDEX DIS_AGAFATPER_REGISTRE_FK_I ON DIS_REGISTRE(AGAFAT_PER);

-- #316: Ampliar el camp comentari de 256 caràcters a 4096 caràcters
ALTER TABLE DIS_CONT_MOV MODIFY COMENTARI character varying(3940);
ALTER TABLE DIS_CONT_COMMENT MODIFY TEXT character varying(4000);