-- #157 Distribucio es queda sense connexions a BBDD 
-- S'ha de millorar la consulta de registres. Es crea una columna nova per determinar si està pendent

-- Afegeix una columna de processament
ALTER TABLE DISTRIBUCIO.DIS_REGISTRE ADD PENDENT BOOLEAN NOT NULL DEFAULT TRUE;
-- Posa com a processades les que tinguin l'estat de processat
UPDATE DIS_REGISTRE SET PENDENT = FALSE
WHERE PROCES_ESTAT IN ('BUSTIA_PROCESSADA', 'BACK_PENDENT', 'BACK_REBUDA', 'BACK_PROCESSADA', 'BACK_REBUTJADA', 'BACK_ERROR');
-- Crea un índex per a la nova columna 
CREATE INDEX DIS_REGISTRE_PENDENT_I ON DISTRIBUCIO.DIS_REGISTRE (PENDENT);

-- #171 Modificar tamany de camps de la taula DIS_REGISTRE 
-- S'han d'igualar els camps EXPOSA, SOLICITA, MOTIU_REBUIG al regweb3
-- i posar-los com a LOB.

-- Per canviar el tipus de la columna:

-- 1 Canvia el nom de la columna actual
ALTER TABLE DIS_REGISTRE RENAME COLUMN EXPOSA TO EXPOSA2;
ALTER TABLE DIS_REGISTRE RENAME COLUMN SOLICITA TO SOLICITA2;
ALTER TABLE DIS_REGISTRE RENAME COLUMN MOTIU_REBUIG TO MOTIU_REBUIG2;
-- 2 Afegeix les noves columnes
ALTER TABLE DIS_REGISTRE ADD EXPOSA text;
ALTER TABLE DIS_REGISTRE ADD SOLICITA text;
ALTER TABLE DIS_REGISTRE ADD MOTIU_REBUIG text;
-- 3 Copia les dades
UPDATE DIS_REGISTRE SET EXPOSA=EXPOSA2;
UPDATE DIS_REGISTRE SET SOLICITA=SOLICITA2;
UPDATE DIS_REGISTRE SET MOTIU_REBUIG=MOTIU_REBUIG2;
-- 4 Esborra les columnes antigues
ALTER TABLE DIS_REGISTRE DROP COLUMN EXPOSA2;
ALTER TABLE DIS_REGISTRE DROP COLUMN SOLICITA2;
ALTER TABLE DIS_REGISTRE DROP COLUMN MOTIU_REBUIG2;
-- 5 Refà l'índex
REINDEX INDEX DIS_REGISTRE_PK;
