
-- #235: Millora de regles. Manteniment de backoffices

CREATE TABLE DIS_BACKOFFICE
(
    ID BIGSERIAL NOT NULL,
    TIPUS CHARACTER VARYING(256) NOT NULL,
    CODI CHARACTER VARYING(20) NOT NULL,
    NOM CHARACTER VARYING(64) NOT NULL,
    URL CHARACTER VARYING(256) NOT NULL,
    USUARI CHARACTER VARYING(64),
    CONTRASENYA CHARACTER VARYING(64),
    INTENTS INTEGER,
    TEMPS_ENTRE_INTENTS INTEGER,
    ENTITAT_ID BIGINT NOT NULL,
    CREATEDBY_CODI CHARACTER VARYING(64 CHAR),
    CREATEDDATE TIMESTAMP WITHOUT TIME ZONE,
    LASTMODIFIEDBY_CODI CHARACTER VARYING(64 CHAR),
    LASTMODIFIEDDATE TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_BACKOFFICE_PK PRIMARY KEY (ID);
ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_ENTITAT_BACKOFFICE_FK FOREIGN KEY (ENTITAT_ID) REFERENCES DIS_ENTITAT(ID);