-- Distribucio 1.0.4

-- #738 Afegir una nova opció d'administrador per poder consultar l'estat de l'execució de les darreres accions massives 

CREATE TABLE DIS_EXECUCIO_MASSIVA (	
	ID 					BIGSERIAL NOT NULL , 
	TIPUS 				VARCHAR(64) NOT NULL, 
	ESTAT 				VARCHAR(64) NOT NULL, 
	USUARI_CODI			VARCHAR(64) NOT NULL, 
	DATA_CREACIO		TIMESTAMP NOT NULL, 
	DATA_INICI			TIMESTAMP, 
	DATA_FINAL			TIMESTAMP, 
	ENTITAT_ID 			BIGSERIAL NOT NULL , 
	PARAMETRES 			VARCHAR(2046),
	CREATEDBY_CODI 		VARCHAR(64), 
	CREATEDDATE 		TIMESTAMP (6), 
	LASTMODIFIEDBY_CODI VARCHAR(64), 
	LASTMODIFIEDDATE 	TIMESTAMP (6)
 );
 
 ALTER TABLE DIS_EXECUCIO_MASSIVA ADD (
  CONSTRAINT DIS_EXECUCIO_MASSIVA_PK PRIMARY KEY (ID));
  
 -- Assigna permisos a la taula
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_EXECUCIO_MASSIVA TO WWW_DISTRIBUCIO;

-- DIS_EXECUCIO_MASSIVA foreign keys

ALTER TABLE DIS_EXECUCIO_MASSIVA ADD CONSTRAINT DIS_EXECMAS_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) REFERENCES DIS_ENTITAT(ID);
ALTER TABLE DIS_EXECUCIO_MASSIVA ADD CONSTRAINT DIS_EXECMAS_USUARI_FK FOREIGN KEY (USUARI_CODI) REFERENCES DIS_USUARI(CODI);

CREATE TABLE DIS_EXECUCIO_MASSIVA_CONT (	
	ID 					BIGSERIAL NOT NULL,
	EXECUCIO_MASSIVA_ID	BIGSERIAL NOT NULL,
	ELEMENT_ID 			BIGSERIAL NOT NULL UNIQUE,
	ELEMENT_NOM 		VARCHAR(2046),
	ELEMENT_TIPUS 		VARCHAR(16) NOT NULL,
	ESTAT 				VARCHAR(64) NOT NULL,
	DATA_CREACIO		TIMESTAMP NOT NULL, 
	DATA_INICI			TIMESTAMP, 
	DATA_FINAL			TIMESTAMP, 
	ERROR				VARCHAR(2046),
	MISSATGE			VARCHAR(2046 CHAR),
	ORDRE				BIGSERIAL NOT NULL,
	CREATEDBY_CODI 		VARCHAR(64), 
	CREATEDDATE 		TIMESTAMP (6), 
	LASTMODIFIEDBY_CODI VARCHAR(64), 
	LASTMODIFIEDDATE 	TIMESTAMP (6)
 );

 ALTER TABLE DIS_EXECUCIO_MASSIVA_CONT ADD (
  CONSTRAINT DIS_EXECUCIO_MASSIVA_CONT_PK PRIMARY KEY (ID));
  
 -- Assigna permisos a la taula
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_EXECUCIO_MASSIVA_CONT TO WWW_DISTRIBUCIO;

-- DIS_EXECUCIO_MASSIVA_CONT foreign keys

ALTER TABLE DIS_EXECUCIO_MASSIVA_CONT ADD CONSTRAINT DIS_EXECMAS_CONT_MASSIVA_FK FOREIGN KEY (EXECUCIO_MASSIVA_ID) REFERENCES DIS_EXECUCIO_MASSIVA(ID);

INSERT INTO DIS_CONFIG_GROUP (CODE,PARENT_CODE,POSITION,DESCRIPTION) VALUES ('SCHEDULLED_EXECUCIONS_MASSIVES','SCHEDULLED','20','Tasca periòdica d''executar les execucions massives pendents');
INSERT INTO DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE) VALUES ('es.caib.distribucio.segonpla.cron.execucio.massiva',null,'Especificar l''expressió ''cron'' indicant l''interval de temps de les execucions de la tasca','SCHEDULLED_EXECUCIONS_MASSIVES','0',false,'CRON',null,null);


-- Millorar el rendiment del localitzador d'annotacions #740

-- #740 Indexar les columnes d'ordre i les que s'utilitzen freqüentment per filtrar

CREATE INDEX DIS_REGISTRE_NUMERO_I ON DIS_REGISTRE (NUMERO);
CREATE INDEX DIS_REGISTRE_EXTRACTE_I ON DIS_REGISTRE (EXTRACTE);
CREATE INDEX DIS_REGISTRE_NUM_ORIG_I ON DIS_REGISTRE (NUM_ORIG);
CREATE INDEX DIS_REGISTRE_DATA_I ON DIS_REGISTRE (DATA);
CREATE INDEX DIS_REGISTRE_PROCES_ESTAT_I ON DIS_REGISTRE (PROCES_ESTAT);
