ALTER TABLE DIS_REGISTRE ALTER COLUMN BACK_OBSERVACIONS TYPE character varying(4000);

-- #109 Afegir codis de municipi, país i província a les anotacions de registre 
-- amplia la columna de la descripció del país
ALTER TABLE DIS_REGISTRE_INTER ALTER COLUMN PAIS TYPE character varying(100);
-- afegeix les noves columnes
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN PAIS_CODI CHARACTER VARYING(4);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN PROVINCIA_CODI CHARACTER VARYING(4);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN MUNICIPI_CODI CHARACTER VARYING(4);