ALTER TABLE DIS_REGISTRE ALTER COLUMN BACK_OBSERVACIONS TYPE character varying(4000);

-- #109 Afegir codis de municipi, país i província a les anotacions de registre 

-- Reanomena la columna pais a pais_codi de la taula d'interessats
ALTER TABLE
	DIS_REGISTRE_INTER
RENAME COLUMN
   PAIS
TO
   PAIS_CODI;
-- Noves columnes
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN PAIS CHARACTER VARYING(100);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN PROVINCIA_CODI CHARACTER VARYING(4);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN MUNICIPI_CODI CHARACTER VARYING(4);