-- #297 Poder marcar bústies com a favorits
-- Oracle:

CREATE TABLE DIS_BUSTIA_FAVORIT
(
    ID                  NUMBER(19,0)        NOT NULL, 
    BUSTIA_ID           NUMBER(19,0)        NOT NULL, 
    USUARI_CODI         VARCHAR2(64 CHAR)   NOT NULL, 
	CREATEDBY_CODI      VARCHAR2(64 CHAR), 
	CREATEDDATE         TIMESTAMP (6), 
	LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR), 
	LASTMODIFIEDDATE    TIMESTAMP (6)
);

ALTER TABLE DIS_BUSTIA_FAVORIT ADD (
CONSTRAINT DIS_BUSTIA_FAV_BUSTIA_FK FOREIGN KEY (BUSTIA_ID)
    REFERENCES DIS_BUSTIA (ID),
CONSTRAINT DIS_BUSTIA_FAV_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES DIS_USUARI (CODI),
CONSTRAINT DIS_USUCRE_BUSTFAV_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES DIS_USUARI (CODI),
CONSTRAINT DIS_USUMOD_BUSTFAV_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES DIS_USUARI (CODI));
	
ALTER TABLE DIS_BUSTIA_FAVORIT 
	ADD CONSTRAINT DIS_BUSTIA_FAV_MULT_UK 
	UNIQUE (
			BUSTIA_ID, 
			USUARI_CODI);
	
CREATE INDEX DIS_BUSTIA_FAV_BUSTIA_FK_I ON DIS_BUSTIA_FAVORIT(BUSTIA_ID);
CREATE INDEX DIS_BUSTIA_FAV_USUARI_FK_I ON DIS_BUSTIA_FAVORIT(USUARI_CODI);

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BUSTIA_FAVORIT TO WWW_DISTRIBUCIO; 

-- Postgresql:

CREATE TABLE DIS_BUSTIA_FAVORIT
(
    ID                  BIGSERIAL        			NOT NULL, 
    BUSTIA_ID           BIGSERIAL        			NOT NULL, 
    USUARI_CODI         character varying(64)   	NOT NULL, 
	CREATEDBY_CODI      character varying(64), 
	CREATEDDATE         timestamp without time zone, 
	LASTMODIFIEDBY_CODI character varying(64), 
	LASTMODIFIEDDATE    timestamp without time zone
);

ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_BUSTIA_FAV_BUSTIA_FK FOREIGN KEY (BUSTIA_ID)
    REFERENCES DIS_BUSTIA (ID);
ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_BUSTIA_FAV_USUARI_FK FOREIGN KEY (USUARI_CODI)
    REFERENCES DIS_USUARI (CODI);
ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_USUCRE_BUSTFAV_FK FOREIGN KEY (CREATEDBY_CODI)
    REFERENCES DIS_USUARI (CODI);
ALTER TABLE ONLY DIS_BUSTIA_FAVORIT ADD CONSTRAINT DIS_USUMOD_BUSTFAV_FK FOREIGN KEY (LASTMODIFIEDBY_CODI)
    REFERENCES DIS_USUARI (CODI);

ALTER TABLE ONLY DIS_BUSTIA_FAVORIT 
	ADD CONSTRAINT DIS_BUSTIA_FAV_MULT_UK 
	UNIQUE (
			BUSTIA_ID, 
			USUARI_CODI);
	
CREATE INDEX DIS_BUSTIA_FAV_BUSTIA_FK_I ON DIS_BUSTIA_FAVORIT(BUSTIA_ID);
CREATE INDEX DIS_BUSTIA_FAV_USUARI_FK_I ON DIS_BUSTIA_FAVORIT(USUARI_CODI);