-- #299 Poder reservar/agafar un assentament abans de marcar-lo com a processat

-- Oracle:
ALTER TABLE DIS_REGISTRE ADD AGAFAT_PER VARCHAR2(64 CHAR);

ALTER TABLE DIS_REGISTRE ADD CONSTRAINT DIS_AGAFATPER_REGISTRE_FK FOREIGN KEY (AGAFAT_PER) REFERENCES DIS_USUARI (CODI);
CREATE INDEX DIS_AGAFATPER_REGISTRE_FK_I ON DIS_REGISTRE(AGAFAT_PER);

-- Postgresql:
ALTER TABLE DIS_REGISTRE ADD AGAFAT_PER VARCHAR2(64 CHAR);

ALTER TABLE DIS_REGISTRE ADD CONSTRAINT DIS_AGAFATPER_REGISTRE_FK FOREIGN KEY (AGAFAT_PER) REFERENCES DIS_USUARI (CODI);
CREATE INDEX DIS_AGAFATPER_REGISTRE_FK_I ON DIS_REGISTRE(AGAFAT_PER);