-- #305 Ampliar detall d'error de custòdia del document

-- Oracle:
ALTER TABLE DIS_REGISTRE RENAME COLUMN PROCES_ERROR TO PROCES_ERROR2;
ALTER TABLE DIS_REGISTRE ADD (PROCES_ERROR CLOB);
UPDATE DIS_REGISTRE SET PROCES_ERROR=PROCES_ERROR2;

-- Postgresql:
ALTER TABLE DIS_REGISTRE RENAME COLUMN PROCES_ERROR TO PROCES_ERROR2;
ALTER TABLE DIS_REGISTRE ADD PROCES_ERROR text;
UPDATE DIS_REGISTRE SET PROCES_ERROR=PROCES_ERROR2;
 





