-- #305 Ampliar detall d'error de custòdia del document

-- Oracle:
ALTER TABLE DIS_REGISTRE MODIFY PROCES_ERROR VARCHAR2(3000 CHAR);

-- Postgresql:
 ALTER TABLE DIS_REGISTRE ALTER COLUMN PROCES_ERROR TYPE CHARACTER VARYING(3000);