-- #316: Ampliar el camp comentari de 256 caràcters a 4096 caràcters
-- Oracle:

ALTER TABLE DIS_CONT_MOV MODIFY COMENTARI VARCHAR2(3940 CHAR);
ALTER TABLE DIS_CONT_COMMENT MODIFY TEXT VARCHAR2(4000 CHAR);

-- Postgresql:

ALTER TABLE DIS_CONT_MOV MODIFY COMENTARI character varying(3940);
ALTER TABLE DIS_CONT_COMMENT MODIFY TEXT character varying(4000);