-- #270: Color capçalera i el logo configurables

-- Oracle:

ALTER TABLE DIS_ENTITAT ADD LOGO_CAP BLOB;
ALTER TABLE DIS_ENTITAT ADD COLOR_FONS VARCHAR2(32 CHAR);
ALTER TABLE DIS_ENTITAT ADD COLOR_LLETRA VARCHAR2(32 CHAR);

-- Postgresql:

ALTER TABLE DIS_ENTITAT ADD LOGO_CAP BLOB;
ALTER TABLE ONLY DIS_ENTITAT ADD COLOR_FONS character varying(32);
ALTER TABLE ONLY DIS_ENTITAT ADD COLOR_LLETRA character varying(32);