package es.caib.distribucio.core.api.service.ws.backoffice;

/**
 * Enumeració amb els possibles valors del tipo de document nti.
 * 
 * @author Limit Tecnologies <limit@limit.es>
 */
public enum NtiTipoDocumento {
	
	RESOLUCIO,
	ACORD,
	CONTRACTE,
	CONVENI,
	DECLARACIO,
	COMUNICACIO,
	NOTIFICACIO,
	PUBLICACIO,
	JUSTIFICANT_RECEPCIO,
	ACTA,
	CERTIFICAT,
	DILIGENCIA,
	INFORME,
	SOLICITUD,
	DENUNCIA,
	ALEGACIO,
	RECURS,
	COMUNICACIO_CIUTADA,
	FACTURA,
	ALTRES_INCAUTATS,
	ALTRES,
	LLEI,
	MOCIO,
	INSTRUCCIO,
	CONVOCATORIA,
	ORDRE_DIA,
	INFORME_PONENCIA,
	DICTAMEN_COMISSIO,
	INICIATIVA_LEGISLATIVA,
	PREGUNTA,
	INTERPELACIO,
	RESPOSTA,
	PROPOSICIO_NO_LLEI,
	ESMENA,
	PROPOSTA_RESOLUCIO,
	COMPAREIXENSA,
	SOLICITUD_INFORMACIO,
	ESCRIT,
	INICIATIVA__LEGISLATIVA,
	PETICIO;
	
	
}
