
# #################################
# PROPIETATS AFEGIDES
# #################################

# Path per a que Distribucio pugui gerstionar arxius en local. S'han d'assignar permisos a l'usuari del jboss.
es.caib.distribucio.fitxers=/app/caib/distribucio


# #################################
# PROPIETATS MODIFICADES
# #################################

###
# Plugin d'ARxiu CAIB
###

## Propietat a modificar, s'ha de posar la mateixa URL sense /uuuid final
es.caib.distribucio.pluginsib.arxiu.caib.conversio.imprimible.url=https://se.caib.es/concsvapi/interna/printable