# #################################
# PROPIETATS AFEGIDES
# #################################

###
# Path d'accés als logs per l'API REST de Comanda amb un usuari amb rol DIS_COM
###
es.caib.distribucio.plugin.fitxer.logs.path=/opt/jboss-eap-7.2/standalone/log