--#719 Augmentar la longitud del camp comentaris

-- Oracle:
ALTER TABLE DIS_CONT_COMMENT ADD TEXT_NEW CLOB;
UPDATE DIS_CONT_COMMENT SET TEXT_NEW = TEXT;
ALTER TABLE DIS_CONT_COMMENT DROP COLUMN TEXT;
ALTER TABLE DIS_CONT_COMMENT RENAME COLUMN TEXT_NEW TO TEXT;

-- Postgresql:
ALTER TABLE DIS_CONT_COMMENT ALTER COLUMN TEXT TYPE TEXT;