-- #423 Millorar el monitor d'integracions 
-- Creació de les taules pel monitor i els paràmetres

CREATE TABLE DIS_MON_INT
(	
   	ID					NUMBER(19,0) 		NOT NULL,
	CODI 				VARCHAR2(64 CHAR) 	NOT NULL, 
	DATA 				TIMESTAMP (6), 
	DESCRIPCIO 			VARCHAR2(1024 CHAR), 
	TIPUS 				VARCHAR2(10 CHAR), 
	TEMPS_RESPOSTA		NUMBER(19,0), 
	ESTAT				VARCHAR2(5 CHAR),
	CODI_USUARI			VARCHAR2(64 CHAR),
	ERROR_DESCRIPCIO	VARCHAR2(1024 CHAR),
	EXCEPCIO_MSG		VARCHAR2(1024 CHAR),
	EXCEPCIO_STACKTRACE	VARCHAR2(2048 CHAR)
);

ALTER TABLE DIS_MON_INT ADD (
  CONSTRAINT DIS_MON_INT_PK PRIMARY KEY (ID));
  


GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_MON_INT TO WWW_DISTRIBUCIO;


CREATE TABLE DIS_MON_INT_PARAM
(	
   	ID					NUMBER(19,0) 			NOT NULL, 
   	MON_INT_ID			NUMBER(19)				NOT NULL,
	NOM		 			VARCHAR2(64 CHAR) 		NOT NULL,
	DESCRIPCIO 			VARCHAR2(1024 CHAR)
);

ALTER TABLE DIS_MON_INT_PARAM ADD (
  CONSTRAINT DIS_MON_INT_PARAM_PK PRIMARY KEY (ID));

ALTER TABLE DIS_MON_INT_PARAM ADD CONSTRAINT DIS_MONINTPARAM_MONINT_FK 
	FOREIGN KEY (MON_INT_ID) REFERENCES DIS_MON_INT(ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_MON_INT_PARAM TO WWW_DISTRIBUCIO;

-- Insereix la propietat per la nova tasca periòdica.
Insert into DIS_CONFIG_GROUP (CODE,PARENT_CODE,POSITION,DESCRIPTION) values ('SCHEDULLED_MON_INT','SCHEDULLED','20','Tasca periòdica d''esborrat de dades antigues del Monitor d''Integracions');
Insert into DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE) values ('es.caib.distribucio.tasca.monitor.integracio.esborrar.antics.periode', '3600000', 'Iterval de temps entre les execucions de la tasca (ms). Per defecte 3600000 ms', 'SCHEDULLED_MON_INT', 0, 0, 'INT');
Insert into DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE) values ('es.caib.distribucio.tasca.monitor.integracio.esborrar.antics.dies', '30', 'Dies màxim d''antigitat per guardar registres. Per defecte 30 dies.', 'SCHEDULLED_MON_INT', 1, 0, 'INT');

-- #425 Afegeix l'entorn a l'assumpte del correu enviat

Insert into DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE) values ('es.caib.distribucio.default.user.entorn',null,'Entorn on es troba l''aplicació','GENERAL','15','0','TEXT',null,null);

-- #398 Separar la secció plugins de l'aplicació de les propietats de configuració 
 
DELETE FROM DIS_CONFIG_GROUP WHERE CODE LIKE 'PLUGINS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 3 WHERE CODE LIKE 'ARXIU';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 4 WHERE CODE LIKE 'UNITATS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 5 WHERE CODE LIKE 'GES_DOC';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 6 WHERE CODE LIKE 'USUARIS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 7 WHERE CODE LIKE 'DISTRIBUCIO';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 8 WHERE CODE LIKE 'PROCEDIMENTS';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 9 WHERE CODE LIKE 'DADES_EXTERNES';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 10 WHERE CODE LIKE 'SIGNATURA';
UPDATE DIS_CONFIG_GROUP SET PARENT_CODE = NULL, POSITION = 11 WHERE CODE LIKE 'VALID_SIGN';

-- #424 No permetre reenviar registres a la bustia principal
Insert into DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE) values ('es.caib.distribucio.no.permetre.reenviar.bustia.default.entitat',null,'Marcar per no permetre reenviar anotacions a la bústia per defecte de l''entitat','GENERAL','11','0','BOOL',null,null);
