
-- #235: Millora de regles. Manteniment de backoffices

CREATE TABLE DIS_BACKOFFICE
(
    ID NUMBER(19) NOT NULL,
    TIPUS VARCHAR2(256 CHAR) NOT NULL,
    CODI VARCHAR2(20 CHAR) NOT NULL,
    NOM VARCHAR2(64 CHAR) NOT NULL,
    URL VARCHAR2(256 CHAR) NOT NULL,
    USUARI VARCHAR2(64 CHAR),
    CONTRASENYA VARCHAR2(64 CHAR),
    INTENTS NUMBER(10,0),
    TEMPS_ENTRE_INTENTS NUMBER(10,0),
    ENTITAT_ID NUMBER(19) NOT NULL,
    CREATEDBY_CODI VARCHAR2(64 CHAR),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64 CHAR),
    LASTMODIFIEDDATE TIMESTAMP(6)
);

ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_BACKOFFICE_PK PRIMARY KEY (ID);
ALTER TABLE DIS_BACKOFFICE ADD CONSTRAINT DIS_ENTITAT_BACKOFFICE_FK FOREIGN KEY (ENTITAT_ID) REFERENCES DIS_ENTITAT(ID);

GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_BACKOFFICE TO WWW_DISTRIBUCIO;


-- #237: Millora de regles. Modificar definició de la regla

ALTER TABLE DIS_REGLA
ADD (
    BUSTIA_FILTRE_ID NUMBER(19),
    BACKOFFICE_DESTI_ID NUMBER(19)
);

ALTER TABLE DIS_REGLA ADD CONSTRAINT DIS_BUSTIA_FILTRE_REGLA_FK FOREIGN KEY (BUSTIA_FILTRE_ID) REFERENCES DIS_BUSTIA(ID);
ALTER TABLE DIS_REGLA ADD CONSTRAINT DIS_BACKOFFICE_DESTI_REGLA_FK FOREIGN KEY (BACKOFFICE_DESTI_ID) REFERENCES DIS_BACKOFFICE(ID);



-- #250: Ampliació de la columna DIS_REGISTRE.UNITAT_ADM_DESC per igualar-la a DIS_UNITAT_ORGANITZATIVA.DENOMINACIO

ALTER TABLE DIS_REGISTRE MODIFY UNITAT_ADM_DESC VARCHAR2(300 CHAR);


-- #236: Millora de regles. Nou tipus de regla "reenviar a UO"

ALTER TABLE DIS_REGLA
ADD (
    UNITAT_DESTI_ID NUMBER(19)
);

ALTER TABLE DIS_REGLA ADD CONSTRAINT DIS_UNITAT_DESTI_REGLA_FK FOREIGN KEY (UNITAT_DESTI_ID) REFERENCES DIS_UNITAT_ORGANITZATIVA(ID);
