-- #481 Permetre cercar anotacions per procediment

CREATE TABLE DIS_PROCEDIMENT 
(
  ID						NUMBER(19)	    	NOT NULL,
  CODI          			VARCHAR2(64)		NOT NULL,
  NOM						VARCHAR2(256),
  CODISIA					VARCHAR2(64),
  ID_UNITAT_ORGANITZATIVA	NUMBER(19),
  ENTITAT					NUMBER(19),
  CREATEDBY_CODI       		VARCHAR2(64),
  CREATEDDATE          		TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  		VARCHAR2(64),
  LASTMODIFIEDDATE     		TIMESTAMP(6)
);
ALTER TABLE DIS_PROCEDIMENT ADD (
  CONSTRAINT DIS_PROCEDIMENT_PK PRIMARY KEY (ID));

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_UNITAT_FK 
	FOREIGN KEY (ID_UNITAT_ORGANITZATIVA) REFERENCES DIS_UNITAT_ORGANITZATIVA(ID);

ALTER TABLE DIS_PROCEDIMENT ADD CONSTRAINT DIS_PROCEDIMENT_ENTITAT_FK 
	FOREIGN KEY (ENTITAT) REFERENCES DIS_ENTITAT(ID);
	
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_PROCEDIMENT TO WWW_DISTRIBUCIO;

-- #503 Implementar un nou servei REST per comunicar anotacions pendents
ALTER TABLE DIS_BACKOFFICE ADD TIPUS VARCHAR2(32 CHAR) DEFAULT 'SOAP' NOT NULL;