-- #270: Color capçalera i el logo configurables


ALTER TABLE DIS_ENTITAT ADD LOGO_CAP BLOB;
ALTER TABLE DIS_ENTITAT ADD COLOR_FONS VARCHAR2(CHAR 32);
ALTER TABLE DIS_ENTITAT ADD COLOR_LLETRA VARCHAR2(CHAR 32);

