-- Distribucio 0.9.48

-- #557 Nova columna a la taula 'DIS_REGLA' que ens indica si s'aplicarà a un registre presencial o no. 
ALTER TABLE DIS_REGLA ADD PRESENCIAL NUMBER(1);

--#558 Poder canviar títol en classificar
Insert into DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE) values ('es.caib.distribucio.contingut.modificar.titol','0','Permetre modificar el títol d''una anotació en classificar','GENERAL','20','0','BOOL',null,null);

--#567 Poder metadatar assentaments registrals en distribució
Insert into DIS_CONFIG (KEY,VALUE,DESCRIPTION,GROUP_CODE,POSITION,JBOSS_PROPERTY,TYPE_CODE,LASTMODIFIEDBY_CODI,LASTMODIFIEDDATE) values ('es.caib.distribucio.permetre.metadades.registre','0','Permetre metadatar assentaments registrals','GENERAL','21','0','BOOL',null,null);

CREATE TABLE DIS_METADADA
(
  ID                    NUMBER(19)              NOT NULL,
  CODI                  VARCHAR2(64)            NOT NULL,
  NOM                   VARCHAR2(256)           NOT NULL,
  TIPUS                 NUMBER(10)              NOT NULL,
  MULTIPLICITAT         NUMBER(10)              NOT NULL,
  ACTIVA                NUMBER(1)               NOT NULL,
  READ_ONLY             NUMBER(1)               NOT NULL,
  ORDRE                 NUMBER(10)              NOT NULL,
  DESCRIPCIO            VARCHAR2(1024),
  ENTITAT_ID            NUMBER(19)              NOT NULL,
  NO_APLICA				NUMBER(1)				DEFAULT 0,
  VERSION               NUMBER(19)              NOT NULL,
  VALOR 				VARCHAR2(255),
  CREATEDBY_CODI        VARCHAR2(64),
  CREATEDDATE           TIMESTAMP(6),
  LASTMODIFIEDBY_CODI   VARCHAR2(64),
  LASTMODIFIEDDATE      TIMESTAMP(6)
);

ALTER TABLE DIS_METADADA ADD (
  CONSTRAINT DIS_METADADA_PK PRIMARY KEY (ID),
  CONSTRAINT DIS_METADADA_CODI_UK UNIQUE (CODI),
  CONSTRAINT DIS_METADADA_ENTITAT_FK FOREIGN KEY (ENTITAT_ID) 
    REFERENCES DIS_ENTITAT (ID),
  CONSTRAINT DIS_USUCRE_METADADA_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES DIS_USUARI (CODI),
  CONSTRAINT DIS_USUMOD_METADADA_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES DIS_USUARI (CODI));
    
CREATE TABLE DIS_DADA
(
  ID                   NUMBER(19)               NOT NULL,
  ORDRE                NUMBER(10),
  VALOR                VARCHAR2(256 CHAR)       NOT NULL,
  VERSION              NUMBER(19)               NOT NULL,
  METADADA_ID          NUMBER(19)               NOT NULL,
  REGISTRE_ID          NUMBER(19)               NOT NULL,
  CREATEDBY_CODI       VARCHAR2(64 CHAR),
  CREATEDDATE          TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64 CHAR),
  LASTMODIFIEDDATE     TIMESTAMP(6)
);

ALTER TABLE DIS_DADA ADD (
  CONSTRAINT DIS_DADA_PK PRIMARY KEY (ID),
  CONSTRAINT DIS_DADA_MULT_UK UNIQUE (METADADA_ID, REGISTRE_ID, ORDRE),
  CONSTRAINT DIS_REGISTRE_DADA_FK FOREIGN KEY (REGISTRE_ID) 
    REFERENCES DIS_REGISTRE (ID),
  CONSTRAINT DIS_METADADA_DADA_FK FOREIGN KEY (METADADA_ID) 
    REFERENCES DIS_METADADA (ID),
  CONSTRAINT DIS_USUCRE_DADA_FK FOREIGN KEY (CREATEDBY_CODI) 
    REFERENCES DIS_USUARI (CODI),
  CONSTRAINT DIS_USUMOD_DADA_FK FOREIGN KEY (LASTMODIFIEDBY_CODI) 
    REFERENCES DIS_USUARI (CODI));
    
CREATE TABLE DIS_DOMINI
(
  ID                   NUMBER(19)           	NOT NULL,
  CODI                 VARCHAR2(64 CHAR)		NOT NULL,
  NOM                  VARCHAR2(256 CHAR)	    NOT NULL,
  DESCRIPCIO           VARCHAR2(256 CHAR),
  CONSULTA             VARCHAR2(256 CHAR)       NOT NULL,
  CADENA               VARCHAR2(256 CHAR)       NOT NULL,
  CONTRASENYA          VARCHAR2(256 CHAR)       NOT NULL,
  ENTITAT_ID           NUMBER(19)           	NOT NULL,
  CREATEDDATE          TIMESTAMP(6),
  CREATEDBY_CODI       VARCHAR2(64 CHAR),
  LASTMODIFIEDDATE     TIMESTAMP(6),
  LASTMODIFIEDBY_CODI  VARCHAR2(64 CHAR)
);

ALTER TABLE DIS_DOMINI ADD (
  CONSTRAINT DIS_DOMINI_PK PRIMARY KEY (ID));

ALTER TABLE DIS_DOMINI ADD (
  CONSTRAINT DIS_ENTITAT_DOMINI_Fk FOREIGN KEY (ENTITAT_ID) 
    REFERENCES DIS_ENTITAT (ID));
    
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_METADADA TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_DADA TO WWW_DISTRIBUCIO;
GRANT SELECT, UPDATE, INSERT, DELETE ON DIS_DOMINI TO WWW_DISTRIBUCIO;

-- #576 Revisar per què les propietats fixades a null no s'actualitzen
-- Actualitza la clau antiga amb la nova clau
UPDATE DIS_CONFIG
SET KEY  = REPLACE(KEY, 'csv.definicio', 'csv_generation_definition')
WHERE KEY LIKE  'es.caib.distribucio%.plugin.arxiu.caib.csv.definicio';


