-- #109 Afegir codis de municipi, país i província a les anotacions de registre 

-- Oracle

-- Reanomena la columna pais a pais_codi de la taula d'interessats
ALTER TABLE
	DIS_REGISTRE_INTER
RENAME COLUMN
   PAIS
TO
   PAIS_CODI;
-- Noves columnes
ALTER TABLE DIS_REGISTRE_INTER ADD PAIS VARCHAR2(100);
ALTER TABLE DIS_REGISTRE_INTER ADD PROVINCIA_CODI VARCHAR2(4);
ALTER TABLE DIS_REGISTRE_INTER ADD MUNICIPI_CODI VARCHAR2(4);


-- PostgreSQL

-- Reanomena la columna pais a pais_codi de la taula d'interessats
ALTER TABLE
	DIS_REGISTRE_INTER
RENAME COLUMN
   PAIS
TO
   PAIS_CODI;
-- Noves columnes
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN PAIS CHARACTER VARYING(100);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN PROVINCIA_CODI CHARACTER VARYING(4);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN MUNICIPI_CODI CHARACTER VARYING(4);
