-- #109 Afegir codis de municipi, país i província a les anotacions de registre 

-- Oracle
-- amplia la columna de la descripció del país
ALTER TABLE DIS_REGISTRE_INTER MODIFY PAIS VARCHAR2(100);
-- afegeix les noves columnes
ALTER TABLE DIS_REGISTRE_INTER ADD PAIS_CODI VARCHAR2(4);
ALTER TABLE DIS_REGISTRE_INTER ADD PROVINCIA_CODI VARCHAR2(4);
ALTER TABLE DIS_REGISTRE_INTER ADD MUNICIPI_CODI VARCHAR2(4);

-- PostgreSQL
-- amplia la columna de la descripció del país
ALTER TABLE DIS_REGISTRE_INTER ALTER COLUMN PAIS TYPE character varying(100);
-- afegeix les noves columnes
ALTER TABLE DIS_REGISTRE_INTER ADD PAIS_CODI VARCHAR2(4);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN PROVINCIA_CODI CHARACTER VARYING(4);
ALTER TABLE DIS_REGISTRE_INTER ADD COLUMN MUNICIPI_CODI CHARACTER VARYING(4);