-- #171 Modificar tamany de camps de la taula DIS_REGISTRE 
-- S'han d'igualar els camps EXPOSA, SOLICITA, MOTIU_REBUIG al regweb3
-- i posar-los com a LOB.

-- Oracle

-- Per canviar el tipus de la columna:

-- 1 Canvia el nom de la columna actual
ALTER TABLE DIS_REGISTRE RENAME COLUMN EXPOSA TO EXPOSA2;
ALTER TABLE DIS_REGISTRE RENAME COLUMN SOLICITA TO SOLICITA2;
ALTER TABLE DIS_REGISTRE RENAME COLUMN MOTIU_REBUIG TO MOTIU_REBUIG2;
-- 2 Afegeix les noves columnes
ALTER TABLE DIS_REGISTRE ADD (EXPOSA CLOB);
ALTER TABLE DIS_REGISTRE ADD (SOLICITA CLOB);
ALTER TABLE DIS_REGISTRE ADD (MOTIU_REBUIG CLOB);
-- 3 Copia les dades
UPDATE DIS_REGISTRE SET EXPOSA=EXPOSA2;
UPDATE DIS_REGISTRE SET SOLICITA=SOLICITA2;
UPDATE DIS_REGISTRE SET MOTIU_REBUIG=MOTIU_REBUIG2;
-- 4 Esborra les columnes antigues
ALTER TABLE DIS_REGISTRE DROP COLUMN EXPOSA2;
ALTER TABLE DIS_REGISTRE DROP COLUMN SOLICITA2;
ALTER TABLE DIS_REGISTRE DROP COLUMN MOTIU_REBUIG2;
-- 5 Refà l'índex
ALTER INDEX DIS_REGISTRE_PK REBUILD;


-- Postgres

-- Per canviar el tipus de la columna:

-- 1 Canvia el nom de la columna actual
ALTER TABLE DIS_REGISTRE RENAME COLUMN EXPOSA TO EXPOSA2;
ALTER TABLE DIS_REGISTRE RENAME COLUMN SOLICITA TO SOLICITA2;
ALTER TABLE DIS_REGISTRE RENAME COLUMN MOTIU_REBUIG TO MOTIU_REBUIG2;
-- 2 Afegeix les noves columnes
ALTER TABLE DIS_REGISTRE ADD EXPOSA text;
ALTER TABLE DIS_REGISTRE ADD SOLICITA text;
ALTER TABLE DIS_REGISTRE ADD MOTIU_REBUIG text;
-- 3 Copia les dades
UPDATE DIS_REGISTRE SET EXPOSA=EXPOSA2;
UPDATE DIS_REGISTRE SET SOLICITA=SOLICITA2;
UPDATE DIS_REGISTRE SET MOTIU_REBUIG=MOTIU_REBUIG2;
-- 4 Esborra les columnes antigues
ALTER TABLE DIS_REGISTRE DROP COLUMN EXPOSA2;
ALTER TABLE DIS_REGISTRE DROP COLUMN SOLICITA2;
ALTER TABLE DIS_REGISTRE DROP COLUMN MOTIU_REBUIG2;
-- 5 Refà l'índex
REINDEX INDEX DIS_REGISTRE_PK;
