//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.24 at 10:37:35 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:es:caib:sistra2:xml:formulario:v1:model")
package es.caib.distribucio.backoffice.utils.sistra.formulario;
